name: SDK Issue
description: Report an issue with Ren'Py files or SQL schema
title: "[SDK] "
labels: ["workspace: sdk"]
body:
  - type: markdown
    attributes:
      value: |
        Report issues or suggest improvements for the SDK (Ren'Py scripts and SQL schema).

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of SDK issue is this?
      options:
        - Bug in Ren'Py code
        - SQL schema issue
        - Documentation error
        - Feature request
        - Compatibility issue
        - Example code issue
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the issue or what are you suggesting?
      placeholder: Describe the issue or feature request...
    validations:
      required: true

  - type: input
    id: renpy_version
    attributes:
      label: Ren'Py Version
      description: Which version of Ren'Py are you using?
      placeholder: "8.1.3"

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Relevant Ren'Py code or SQL if applicable
      placeholder: Paste code here...
      render: python
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen? (for bugs)
      placeholder: What you expected to happen...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or examples?
      placeholder: Additional context...
    validations:
      required: false
